server:
  port: 8080
  servlet:
    context-path: /bootdemo
mybatis:
  typeAliasesPackage: com.bootdemo.domain
  mapperLocations: classpath:mapper/*.xml
spring:
  jpa:
    open-in-view: false
  redis:
    database: 0
    host: 101.132.33.164
    port: 6379
    password: yanyuzjm
    jedis:
      pool:
        max-idle: 30
        max-active: 8
        max-wait: 10000
        min-idle: 10
  thymeleaf:
    cache: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://101.132.33.164:3306/trains?useSSL=false&autoReconnect=true&allowMultiQueries=true
    username: yanyu
    password: usrzjm
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
logging:
  file:
    name: bootdemo.log
  level:
    org:
      springframework:
        web: debug
    com:
      bootdemo:
        dao: debug